stages:
  - test
  - deploy
  - tf_apply

test & assembly:
  stage: test
  image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
  script:
  - >-
    sbt
    -sbt-dir .sbt
    -ivy .ivy2
    -mem 2048
    app/assembly
  cache:
    paths:
    - .sbt
    - .ivy2
  artifacts:
    paths:
    - target/scala-2.12/t99.jar
    expire_in: 30 days

scalafmt:
  stage: test
  image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
  script:
  - >-
    sbt
    -sbt-dir .sbt
    -ivy .ivy2
    -mem 2048
    scalafmt::test
    test:scalafmt::test
    sbt:scalafmt::test
  cache:
    paths:
    - .sbt
    - .ivy2

terraform plan:
  stage: test
  image:
    name: hashicorp/terraform:0.11.13
    entrypoint: [""]
  script:
    - cd terraform
    - terraform init
    - terraform fmt -check=true -diff=true
    - terraform validate
    - terraform plan
  cache:
    paths:
      - terraform/.terrafrom
  artifacts:
    paths:
      - terraform/.terraform
    expire_in: 1 week

deploy prod:
  stage: deploy
  image:
    name: nomadblacky/serverless:1.39.1
    entrypoint:
      - ""
  environment:
    name: production
  before_script:
    - npm install --save-dev serverless-plugin-tracing
  script:
    - serverless deploy --stage prod
  cache:
    paths:
      - node_modules/
  only:
    - master

terraform apply:
  stage: tf_apply
  dependencies:
    - terraform plan
  image:
    name: hashicorp/terraform:0.11.13
    entrypoint: [""]
  script:
    - cd terraform
    - terraform apply
  only:
    - master
