service: t99-analytics

frameworkVersion: "=1.39.1"

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1


package:
  artifact: target/scala-2.12/t99.jar

functions:
  t99:
    role: t99FunctionRole
    handler: t99.lambda.Handler
    timeout: 30
    events:
      - http:
          path: execute
          method: post
    environment:
      AUTH_TOKEN: ${env:T99_AUTH_TOKEN}
      TWITTER_CONSUMER_KEY: ${env:T99_TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${env:T99_TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_KEY: ${env:T99_TWITTER_ACCESS_KEY}
      TWITTER_ACCESS_SECRET: ${env:T99_TWITTER_ACCESS_SECRET}

resources:
  Resources:
    t99FunctionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: T99FunctionRole-${self:provider.stage}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: t99FunctionPolicy-${self:provider.stage}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        -
                          - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - rekognition:DetectText
                  Resource: "*"
